apiVersion: v1
kind: Service
metadata:
  name: springk8sservice
  namespace: testnsspringk8s
spec:
  selector:
    app: springk8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080